inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Uses [1, 2, 3] rather than [ 1, 2, 3 ]
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# In my personal projects, I like `'` around strings unless needed.
# It tells the reader that no string interpolation or escaped characters are present.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true
